# Generated by Django 6.0.3 on 2026-03-31 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_assignment_submission_peerreview_delete_choice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='required_reviews_per_student',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='peerreview',
            name='is_approved_by_teacher',
            field=models.BooleanField(default=False, help_text='Если True, студент-автор может видеть этот отзыв'),
        ),
        migrations.AlterField(
            model_name='peerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peerreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='polls.submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polls.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code_content',
            field=models.TextField(help_text='Код, отправленный студентом'),
        ),
    ]
