# Generated by Django 6.0.3 on 2026-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_peerreview_is_discarded_alter_assignment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='is_approved_by_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code_content',
            field=models.TextField(),
        ),
    ]
